In [7]:
data = ({'_id': '6229b694bf76c6304096974a', 'type': 'strawberries', 'quantity': 7},
{'_id': '6229b694bf76c6304096974b', 'type': 'bananas', 'quantity': 100},
{'_id': '6229b694bf76c6304096974c', 'type': 'apples', 'quantity': 7})

In [9]:
new_data = pd.DataFrame(data)

In [10]:
new_data

                        _id          type  quantity
0  6229b694bf76c6304096974a  strawberries         7
1  6229b694bf76c6304096974b       bananas       100
2  6229b694bf76c6304096974c        apples         7

In [18]:
clust = "mongodb+srv://Nelson:blessing@cluster0.ieu4h.mongodb.net/test?retryWrites=true&w=majority"
client = pymongo.MongoClient(clust)

In [19]:
client.list_database_names()

['sample_airbnb',
 'sample_analytics',
 'sample_geospatial',
 'sample_mflix',
 'sample_restaurants',
 'sample_supplies',
 'sample_training',
 'sample_weatherdata',
 'admin',
 'local']

In [20]:
db = client.sample_airbnb

In [21]:
db.list_collection_names()

['listingsAndReviews']

In [23]:
reviews = db.listingsAndReviews

In [35]:
%%time
results = reviews.find()

Wall time: 0 ns

In [36]:
%%time
import pandas as pd
real = pd.DataFrame(results)

Wall time: 1min 46s

In [29]:
%%time
reviews_db = pd.json_normalize(list(results))

Wall time: 47.5 s

In [42]:
reviews_db.head(1)

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,interaction,house_rules,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,last_scraped,calendar_last_scraped,first_review,last_review,accommodates,bedrooms,beds,number_of_reviews,bathrooms,amenities,price,security_deposit,cleaning_fee,extra_people,guests_included,reviews,images.thumbnail_url,images.medium_url,images.picture_url,images.xl_picture_url,host.host_id,host.host_url,host.host_name,host.host_location,host.host_about,host.host_response_time,host.host_thumbnail_url,host.host_picture_url,host.host_neighbourhood,host.host_response_rate,host.host_is_superhost,host.host_has_profile_pic,host.host_identity_verified,host.host_listings_count,host.host_total_listings_count,host.host_verifications,address.street,address.suburb,address.government_area,address.market,address.country,address.country_code,address.location.type,address.location.coordinates,address.location.is_location_exact,availability.availability_30,availability.availability_60,availability.availability_90,availability.availability_365,review_scores.review_scores_accuracy,review_scores.review_scores_cleanliness,review_scores.review_scores_checkin,review_scores.review_scores_communication,review_scores.review_scores_location,review_scores.review_scores_value,review_scores.review_scores_rating,weekly_price,monthly_price,reviews_per_month
0,10006546,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,Privileged views of the Douro River and Ribeir...,Fantastic duplex apartment with three bedrooms...,"In the neighborhood of the river, you can find...",Lose yourself in the narrow streets and stairc...,Transport: • Metro station and S. Bento railwa...,We are always available to help guests. The ho...,"Cot - 10 € / night Dog - € 7,5 / night",Make the house your home...,House,Entire home/apt,Real Bed,2,30,moderate,2019-02-16 05:00:00,2019-02-16 05:00:00,2016-01-03 05:00:00,2019-01-20 05:00:00,8,3.0,5.0,51,1.0,"[TV, Cable TV, Wifi, Kitchen, Paid parking off...",80.00,200.00,35.00,15.00,6,"[{'_id': '58663741', 'date': 2016-01-03 05:00:...",,,https://a0.muscache.com/im/pictures/e83e702f-e...,,51399391,https://www.airbnb.com/users/show/51399391,Ana&Gonçalo,"Porto, Porto District, Portugal","Gostamos de passear, de viajar, de conhecer pe...",within an hour,https://a0.muscache.com/im/pictures/fab79f25-2...,https://a0.muscache.com/im/pictures/fab79f25-2...,,100.0,False,True,True,3,3,"[email, phone, reviews, jumio, offline_governm...","Porto, Porto, Portugal",,"Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, V...",Porto,Portugal,PT,Point,"[-8.61308, 41.1413]",False,28,47,74,239,9.0,9.0,10.0,10.0,10.0,9.0,89.0,NaN,NaN,NaN

In [43]:
real.head(1)

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,interaction,house_rules,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,last_scraped,calendar_last_scraped,first_review,last_review,accommodates,bedrooms,beds,number_of_reviews,bathrooms,amenities,price,security_deposit,cleaning_fee,extra_people,guests_included,images,host,address,availability,review_scores,reviews,weekly_price,monthly_price,reviews_per_month
0,10006546,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,Privileged views of the Douro River and Ribeir...,Fantastic duplex apartment with three bedrooms...,"In the neighborhood of the river, you can find...",Lose yourself in the narrow streets and stairc...,Transport: • Metro station and S. Bento railwa...,We are always available to help guests. The ho...,"Cot - 10 € / night Dog - € 7,5 / night",Make the house your home...,House,Entire home/apt,Real Bed,2,30,moderate,2019-02-16 05:00:00,2019-02-16 05:00:00,2016-01-03 05:00:00,2019-01-20 05:00:00,8,3.0,5.0,51,1.0,"[TV, Cable TV, Wifi, Kitchen, Paid parking off...",80.00,200.00,35.00,15.00,6,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51399391', 'host_url': 'https://w...","{'street': 'Porto, Porto, Portugal', 'suburb':...","{'availability_30': 28, 'availability_60': 47,...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '58663741', 'date': 2016-01-03 05:00:...",NaN,NaN,NaN

In [1]:
json_list = [
    { 
        'class': 'Year 1', 
        'student count': 20, 
        'room': 'Yellow',
        'info': {
            'teachers': { 
                'math': 'Rick Scott', 
                'physics': 'Elon Mask' 
            }
        },
        'students': [
            { 
                'name': 'Tom', 
                'sex': 'M', 
                'grades': { 'math': 66, 'physics': 77 } 
            },
            { 
                'name': 'James', 
                'sex': 'M', 
                'grades': { 'math': 80, 'physics': 78 } 
            },
        ]
    },
    { 
        'class': 'Year 2', 
        'student count': 25, 
        'room': 'Blue',
        'info': {
            'teachers': { 
                'math': 'Alan Turing', 
                'physics': 'Albert Einstein' 
            }==
        },
        'students': [
            { 'name': 'Tony', 'sex': 'M' },
            { 'name': 'Jacqueline', 'sex': 'F' },
        ]
    },
]

In [5]:
import pandas as pd

In [8]:
table1 = pd.json_normalize(json_list)

In [9]:
table1

,class,student count,room,students,info.teachers.math,info.teachers.physics
0,Year 1,20,Yellow,"[{'name': 'Tom', 'sex': 'M', 'grades': {'math'...",Rick Scott,Elon Mask
1,Year 2,25,Blue,"[{'name': 'Tony', 'sex': 'M'}, {'name': 'Jacqu...",Alan Turing,Albert Einstein

In [55]:
table = pd.json_normalize(json_list, record_path=['students'], meta=['class', 'room', ['info', 'teachers', 'math']])
table.head()

,name,sex,grades.math,grades.physics,class,room,info.teachers.math
0,Tom,M,66.0,77.0,Year 1,Yellow,Rick Scott
1,James,M,80.0,78.0,Year 1,Yellow,Rick Scott
2,Tony,M,NaN,NaN,Year 2,Blue,Alan Turing
3,Jacqueline,F,NaN,NaN,Year 2,Blue,Alan Turing